name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: composer install
      - name: Install npm dependencies
        run: npm i
        
#       - name: Setup Laravel
#         run: |
#           echo ${{ secrets.DOT_ENV }} >  .env
#           ls -a
          
#       - run: cat .env
        
#       - name: Run phpunit tests
#         run: vendor/bin/phpunit tests
      - name: Run jest tests
        run: npm run test
        
      - name: Build js
        run: npm run prod
        
      - name: Copy code to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: cederlink.johngachihi.com/public_html/IAP_CAT2
          host: johngachihi.com
          username: johndpwi
          port: 21098
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
