name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Composer dependencies
        run: composer install
      - name: Install npm dependencies
        run: npm i
        
      - name: Setup Laravel for tests
        run: |
          cp .env.example .env
          php artisan key:generate
        
      - name: Run phpunit tests
        run: vendor/bin/phpunit tests
      - name: Run jest tests
        run: npm run test
        
      - name: Build js
        env:
          REACT_APP_API_URL: "https://cederlink.johngachihi.com"
          SASS_PATH: ./node_modules
        run: npm run prod
      
      - name: Compress project
        run: zip -r project.zip . -x '*node_modules*' .env
      - run: ls *.zip
        
      - name: Copy code to server
        uses: appleboy/scp-action@master
        with:
          source: project.zip
          target: cederlink.johngachihi.com/public_html/Cederlinks
          host: johngachihi.com
          username: johndpwi
          port: 21098
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          
      - name: Extract project on server
        uses: appleboy/ssh-action@master
        with:
          host: johngachihi.com
          username: johndpwi
          port: 21098
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd cederlink.johngachihi.com/public_html/Cederlinks
            unzip -o project.zip
            rm project.zip
