name: CI

on:
  push:
    branches: master
    path-ignore:
      - 'tests/**'
      - '.editorconfig'
      - '.eslintrc.js'
      - '.gitignore'
      - 'jest.config.js'
      - 'jest.setup.js'
      - 'README.md'
      - 'setupTests.js'
      - 'tsconfig.json'

jobs:
  build-test-laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install

      - name: Run Laravel tests
        run: |
          cp .env.example .env
          php artisan key:generate
          vendor/bin/phpunit tests
          rm .env

      - name: Compress vendor
        run: zip -r vendor.zip vendor

      - name: Upload vendor
        uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: vendor.zip

  build-test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm i

      - name: Run jest tests
        run: npm run test

      - name: Build js
        env:
          REACT_APP_API_URL: "https://site.cederlinks.com"
          APP_URL: "https://site.cederlinks.com"
          IMAGES_URL: "https://site.cederlinks.com/storage/images"
          SASS_PATH: ./node_modules
        run: npm run prod

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  upload:
    runs-on: ubuntu-latest
    needs: [build-test-laravel, build-test-js]
    steps:
      - uses: actions/checkout@v2

      - name: Download vendor
        uses: actions/download-artifact@v2
        with:
          name: vendor

      - name: Extract vendor
        run: |
          unzip vendor.zip
          rm vendor.zip

      - name: Download public
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Compress project
        run: zip -r project.zip . -x '*node_modules*' '*storage*' .env

      - name: Upload project archive
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: project.zip
